---
- name: ssh-disable-root
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: PermitRootLogin no
  notify: ssh-changed

- name: root-rm-authorized-keys
  ansible.builtin.file:
    path: /root/.ssh/authorized_keys
    state: absent
