---
- name: Install bind9
  ansible.builtin.package:
    state: present
    name: "bind9"

- name: Add named.conf
  ansible.builtin.copy:
    src: "named.conf"
    dest: "/etc/bind/named.conf"
    owner: "root"
    group: "bind"
    mode: "0644"
  notify: Reload bind

- name: Add named.conf.local
  ansible.builtin.copy:
    src: "named.conf.local"
    dest: "/etc/bind/named.conf.local"
    owner: "root"
    group: "bind"
    mode: "0644"
  notify: Reload bind

- name: Add named.conf.options
  ansible.builtin.template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    owner: "root"
    group: "bind"
    mode: "0644"
  notify: Reload bind

- name: Add home.db
  ansible.builtin.template:
    src: "home.db.j2"
    dest: "/etc/bind/home.db"
    owner: "root"
    group: "bind"
    mode: "0644"
  notify: Reload bind

- name: Add named.conf.blocked
  ansible.builtin.template:
    src: "blocked.conf.j2"
    dest: "/etc/bind/named.conf.blocked"
    owner: "root"
    group: "bind"
    mode: "0644"
  notify: Reload bind

- name: Add blocked.db
  ansible.builtin.copy:
    src: "blocked.db"
    dest: "/etc/bind/blocked.db"
    owner: "root"
    group: "bind"
    mode: "0644"
  notify: Reload bind

- name: Start bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
