---
- name: inst-cockpit
  apt:
    name: cockpit
    state: latest

- name: etc-cockpit-cockpit.conf
  copy:
    src: cockpit.conf
    dest: /etc/cockpit/cockpit.conf
  notify: service-cockpit-restart

- name: service-cockpit
  service:
    name: cockpit
    state: started
    enabled: yes

- name: user-cockpit
  user:
    name: cockpit
    home: /home/cockpit
    shell: /bin/bash
