---
- name: Set kernel args
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ kernelargs }}"'
  notify:
    - Rebuild grub conf
    - Rebuild grub grubby
  when: ansible_facts['os_family'] == "RedHat"
