---
- name: Restart ssh
  ansible.builtin.service:
    name: "{{ global_handlers_ssh_service }}"
    state: restarted

- name: Restart journald
  listen: journald-changed
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  notify: Flush journald

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Flush journald
  ansible.builtin.command:
    cmd: /usr/bin/journalctl --flush
  changed_when: true

- name: Rebuild grub conf
  ansible.builtin.command:
    cmd: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  notify: Reboot NOW
  changed_when: true

- name: Rebuild grub grubby
  ansible.builtin.command:
    argv:
      - /usr/sbin/grubby
      - --update-kernel
      - ALL
      - --args
      - "{{ kernelargs }}"
  notify: Reboot NOW
  changed_when: true

- name: Run iptables-save # noqa command-instead-of-module
  listen: iptables-changed
  ansible.builtin.command:
    cmd: service iptables save
  changed_when: true

- name: Run apt autoremove
  ansible.builtin.command:
    cmd: /usr/bin/apt -y autoremove
  changed_when: true

- name: Reboot NOW
  ansible.builtin.reboot:
