---
- name: ssh-restart
  listen: ssh-changed
  service:
    name: "{{ ssh_service }}"
    state: restarted

- name: journald-restart
  listen: journald-changed
  service:
    name: systemd-journald
    state: restarted
  notify: journald-flush

- name: docker-restart
  listen: docker-changed
  service:
    name: docker
    state: restarted

- name: journald-flush
  command:
    cmd: /usr/bin/journalctl --flush

- name: grub-rebuild
  listen: kernel-changed
  command:
    cmd: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  notify: reboot

- name: iptables-save # noqa command-instead-of-module
  listen: iptables-changed
  command:
    cmd: service iptables save

- name: apt-autoremove
  command:
    cmd: /usr/bin/apt -y autoremove

- name: reboot-host-now
  listen: reboot
  reboot:
