---
- name: Restart ssh
  listen: ssh-changed
  ansible.builtin.service:
    name: "{{ ssh_service }}"
    state: restarted

- name: Restart journald
  listen: journald-changed
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  notify: journald-flush

- name: Restart docker
  listen: docker-changed
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Flush journald
  ansible.builtin.command:
    cmd: /usr/bin/journalctl --flush

- name: Rebuild grub conf
  listen: kernel-changed
  ansible.builtin.command:
    cmd: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
  notify: reboot

- name: Rebuild grub grubby
  listen: kernel-changed
  ansible.builtin.command:
    argv:
      - /usr/sbin/grubby
      - --update-kernel
      - ALL
      - --args
      - "{{ kernelargs }}"
  notify: reboot

- name: Run iptables-save # noqa command-instead-of-module
  listen: iptables-changed
  ansible.builtin.command:
    cmd: service iptables save

- name: Run apt autoremove
  ansible.builtin.command:
    cmd: /usr/bin/apt -y autoremove

- name: Reboot NOW
  listen: reboot
  ansible.builtin.reboot:
