---
- name: network-github-webhook-handler
  docker_network:
    name: github-webhook-handler

- name: network-wiki
  docker_network:
    name: wiki

- name: network_letsencrypt
  docker_network:
    name: letsencrypt

- name: container-github-webhook-handler
  docker_container:
    name: github-webhook-handler
    image: ilikejam/github-webhook-handler
    user: "{{ github_webhook_uid }}:{{ github_webhook_gid }}"
    mounts:
      - type: bind
        source: /var/run/repos
        target: /repos
        read_only: false
      - type: bind
        source: "{{ github_deploy_key_path }}"
        target: "{{ github_deploy_key_path }}"
        read_only: true
      - type: bind
        source: "{{ github_webhook_secret_path }}"
        target: "{{ github_webhook_secret_path }}"
        read_only: true
    networks:
      - name: github-webhook-handler
    purge_networks: true
