---
- name: file-github-secret
  copy:
    dest: "{{ github_webhook_secret_path }}"
    content: "{{ lookup('env','GH_WEBHOOK_SECRET') }}"
    mode: '0400'
    owner: "{{ github_webhook_uid }}"
    group: "{{ github_webhook_uid }}"

- name: file-github-deploy-key
  copy:
    dest: "{{ github_deploy_key_path }}"
    src: ~/.ssh/id_github_deploy
    mode: '0400'
    owner: "{{ github_webhook_uid }}"
    group: "{{ github_webhook_uid }}"

- name: dir-var-run-repos
  file:
    path: /var/run/repos
    state: directory
    mode: '0755'
    owner: "{{ github_webhook_uid }}"
    group: "{{ github_webhook_uid }}"
