---
- name: file-github-secret
  ansible.builtin.copy:
    dest: "{{ github_webhook_secret_path }}"
    content: "{{ lookup('community.general.bitwarden', 'wiki_GH_WEBHOOK_SECRET', field='password')[0] }}"
    mode: '0400'
    owner: '{{ users["github_webhook"]["uid"] }}'
    group: '{{ users["github_webhook"]["gid"] }}'

- name: file-github-deploy-key
  ansible.builtin.template:
    dest: "{{ github_deploy_key_path }}"
    src: id_github_deploy.j2
    mode: '0400'
    owner: '{{ users["github_webhook"]["uid"] }}'
    group: '{{ users["github_webhook"]["gid"] }}'

- name: dir-var-dockerbind-repos
  ansible.builtin.file:
    path: /var/dockerbind/repos
    state: directory
    mode: '0755'
    owner: '{{ users["github_webhook"]["uid"] }}'
    group: '{{ users["github_webhook"]["gid"] }}'

- name: dir-var-dockerbind-repos-wiki
  ansible.builtin.file:
    path: /var/dockerbind/repos/wiki
    state: directory
    mode: '0755'
    owner: '{{ users["github_webhook"]["uid"] }}'
    group: '{{ users["github_webhook"]["gid"] }}'

- name: dir-etc-letsencrypt
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    mode: '0755'
    owner: '{{ users["certbot"]["uid"] }}'
    group: '{{ docker_gid }}'

- name: dir-etc-haproxy
  ansible.builtin.file:
    path: /etc/haproxy
    state: directory
    mode: '0755'
    owner: '{{ users["haproxy"]["uid"] }}'
    group: '{{ users["haproxy"]["gid"] }}'

- name: dircopy-var-dockerbind-webmisc
  ansible.builtin.copy:
    src: icons/
    dest: /var/dockerbind/webmisc
    mode: '0644'
    owner: root
    group: root

- name: dir-var-dockerbind-files
  ansible.builtin.file:
    path: /var/dockerbind/files
    state: directory
    mode: '0755'
    owner: dave
    group: dave

- name: dir-var-dockerbind-vaultwarden
  ansible.builtin.file:
    path: /var/dockerbind/vaultwarden
    state: directory
    mode: '0700'
    owner: "{{ users['vaultwarden']['uid'] }}"
    group: "{{ users['vaultwarden']['gid'] }}"

- name: template-haproxy-cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: restart-container-haproxy
