---
github_webhook_secret_path: "/etc/github_webhook_secret"
github_deploy_key_path: "/etc/id_github_deploy"
domain: "davidstark.name"
wiki_domain: "docs.{{ domain }}"
vaultwarden_domain: "warden.{{ domain }}"
