version: '3'

services:
  wikimongo:
    container_name: wikimongo
    image: mongo:latest
    restart: "no"
    volumes:
      - wikimongo_db:/data/db
      - wikimongo_configdb:/data/configdb
    networks:
      - wiki

  wikifront:
    command: bash -c 'cd /wiki && node wiki configure'
    build: ./wikifront
    image: wiki-js
    container_name: wikifront-init
    restart: "no"
    volumes:
      - /root/.ssh/id_wiki:/id_wiki:ro,Z
    networks:
      - wiki
      - haproxy
    tty: true

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: "no"
    volumes:
      - ./haproxy/bind-init:/usr/local/etc/haproxy:ro,Z
    networks:
      - haproxy
    ports:
      - 80:8080
    user: '1001'
    
volumes:
  wikimongo_db:
  wikimongo_configdb:
    
networks:
  haproxy:
  wiki:
