version: '3'

services:
  wikimongo:
    container_name: wikimongo
    image: mongo:latest
    restart: always
    volumes:
      wikimongo:/data/db
    networks:
      wiki

  wikifront:
    build: ./wiki
    image: wiki-js
    container_name: wikifront
    restart: always
    volumes:
      /root/.ssh/id_wiki:/id_wiki:ro,Z
    networks:
      wiki
      haproxy

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: always
    volumes:
      ./haproxy/bind:/usr/local/etc/haproxy:ro,Z
    networks:
      haproxy
    ports:
      80:8000
    
volumes:
  wikimongo:
    
networks:
  haproxy:
  wiki:
