version: '3'

services:
  wikimongo:
    container_name: wikimongo
    image: mongo:latest
    restart: always
    volumes:
      - wikimongo_db:/data/db
      - wikimongo_configdb:/data/configdb
    networks:
      - wiki

  wikifront:
    build: ./wikifront
    image: wiki-js
    container_name: wikifront
    restart: always
    volumes:
      - /root/.ssh/id_wiki:/id_wiki:ro,Z
    networks:
      - wiki
      - haproxy
    tty: true

  webmisc:
    build: ./webmisc
    image: webmisc
    container_name: webmisc
    restart: always
    volumes:
      - ./webmisc/bind:/var/tmp/serve:ro,Z
    networks:
      - haproxy

  letsencrypt:
    build: ./letsencrypt
    image: letsencrypt
    container_name: letsencrypt
    restart: always
    volumes:
      - letsencrypt_etc:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:rw,Z
    networks:
      - haproxy
    command: bash -c 'sleep 10; while true; do certbot renew --deploy-hook /deploy-hook; sleep 86400; done'
    privileged: true

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: always
    volumes:
      - ./haproxy/bind:/usr/local/etc/haproxy:ro,Z
      - letsencrypt_etc:/etc/letsencrypt:ro
    networks:
      - haproxy
    ports:
      - 80:8080
      - 443:8443
    user: '1001'
    
volumes:
  wikimongo_db:
  wikimongo_configdb:
  letsencrypt_etc:
    
networks:
  haproxy:
  wiki:
