---
- name: Include debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include pi.yml
  ansible.builtin.include_tasks: pi.yml
  when: ansible_facts['architecture'] == "armv7l" or ansible_facts['architecture'] == "aarch64"

- name: Include redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"
