---
- name: redhat | Install debug tools
  ansible.builtin.package:
    state: present
    name:
      - lsof
      - iftop
      - iotop
      - telnet
      - bind-utils
      - tcpdump
      - strace
