---
- name: create-var-log-journal
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
    owner: root
    group: systemd-journal
    mode: 02755

- name: rm-sudoers-90-cloud-init-users
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent

- include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"
