---
- name: get-services
  ansible.builtin.service_facts:

- name: stop-network-services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  when: item in services
  with_items:
    - "rpcbind"
    - "postfix"

- name: uninst-network-packages
  ansible.builtin.package:
    state: absent
    name:
      - rpcbind
      - postfix

- name: remove-default-users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  with_items:
    - "centos"
