---
- name: redhat | Get service info
  ansible.builtin.service_facts:

- name: redhat | Stop unused network services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  when: item in services
  with_items:
    - "rpcbind"
    - "postfix"

- name: redhat | Uninstall unused network services
  ansible.builtin.package:
    state: absent
    name:
      - rpcbind
      - postfix
