---
- name: dir-etc-wireguard
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0711'

- name: cmd-generate-wg-privkey
  shell:
    cmd: umask 077; wg genkey > /etc/wireguard/privatekey
    creates: /etc/wireguard/privatekey

- name: cmd-generate-wg-pubkey
  shell:
    cmd: wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey
    creates: /etc/wireguard/publickey

- name: conf-wireguard-wg0
  copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - never
    - wireguard-init
  notify: "wireguard-changed"

- name: conf-wireguard-etc-services
  lineinfile:
    path: /etc/services
    line: "wireguard	2843/upd"
