---
- name: config | Create /etc/wireguard
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0711'

- name: config | Generate private key
  ansible.builtin.shell:
    cmd: umask 077; wg genkey > /etc/wireguard/privatekey
    creates: /etc/wireguard/privatekey
  tags:
    - never
    - wireguard-init

- name: config | Generate public key
  ansible.builtin.shell:
    cmd: wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey
    creates: /etc/wireguard/publickey
  tags:
    - never
    - wireguard-init

- name: config | Create wg0.conf
  ansible.builtin.copy:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - never
    - wireguard-init
  notify: Restart wg-quick@wg0

- name: config | Add wireguard to /etc/services # noqa no-tabs
  ansible.builtin.lineinfile:
    path: /etc/services
    line: "wireguard	2843/upd"
