---
- name: inst-wireguard
  ansible.builtin.dnf:
    state: present
    name:
      - kmod-wireguard
      - wireguard-tools
      - tcpdump
      - iptables
      - iptables-services
      - qrencode
