---
- include_tasks: install-redhat.yml
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] != "Fedora"
- include_tasks: install-debian.yml
  when: ansible_facts['os_family'] == "Debian"
- include_tasks: config.yml
- include_tasks: iptables.yml
- include_tasks: sysctl.yml
- include_tasks: service.yml
- include_tasks: scripts.yml
