---
- name: service-wireguard
  service:
    name: wg-quick@wg0
    state: started
    enabled: true

- name: service-iptables
  service:
    name: iptables
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: service-netfilter-persistent
  service:
    name: netfilter-persistent
    enabled: true
  when: ansible_facts['os_family'] == "Debian"
