---
- name: service | Start wg-quick@wg0
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started
    enabled: true

- name: service | Start iptables
  ansible.builtin.service:
    name: iptables
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: service | Start netfilter-persistent
  ansible.builtin.service:
    name: netfilter-persistent
    enabled: true
  when: ansible_facts['os_family'] == "Debian"
