---
- name: sysctl | Set net.ipv4.ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-vpn.conf

- name: sysctl | Set net.ipv6.conf.all.forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-vpn.conf
