---
- name: Minimise GPU RAM
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: gpu_mem=16

- name: Disable wifi
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtoverlay=disable-wifi

- name: Disable bluetooth
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtoverlay=disable-bt

- name: Add cpufrequtils
  ansible.builtin.package:
    name: cpufrequtils
    state: present

- name: Start cpufrequtils
  ansible.builtin.service:
    name: cpufrequtils
    state: started
    enabled: true

- name: POE HAT overlay
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtoverlay=rpi-poe

- name: POE HAT 0
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtparam=poe_fan_temp0=70000,poe_fan_temp0_hyst=5000
    regexp: '^dtparam=poe_fan_temp0'

- name: POE HAT 1
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtparam=poe_fan_temp1=72500,poe_fan_temp1_hyst=2500
    regexp: '^dtparam=poe_fan_temp1'

- name: POE HAT 2
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtparam=poe_fan_temp2=75000,poe_fan_temp2_hyst=2500
    regexp: '^dtparam=poe_fan_temp2'

- name: POE HAT 3
  ansible.builtin.lineinfile:
    path: "/boot/firmware/config.txt"
    line: dtparam=poe_fan_temp3=78000,poe_fan_temp3_hyst=3000
    regexp: '^dtparam=poe_fan_temp3'

- name: Check swap
  ansible.builtin.command: swapon -s
  register: check_swap_result
  changed_when: false
  check_mode: false

- name: Disable dphys-swapfile
  ansible.builtin.service:
    name: dphys-swapfile
    state: stopped
    enabled: false

- name: Disable swapfile
  ansible.builtin.command: /sbin/dphys-swapfile swapoff
  when: check_swap_result.stdout
  notify: remove-swap
  changed_when: true

- name: Deinstall pi crap
  ansible.builtin.package:
    state: absent
    purge: true
    name:
      - wpasupplicant
      - bluez
      - bluez-firmware
      - avahi-daemon
      - triggerhappy
      - x11-common
      - libwayland-client0
      - wireless-tools
      - alsa-utils
  notify: apt-autoremove

- name: Stop tty1
  ansible.builtin.service:
    name: getty@tty1
    state: stopped
    enabled: false

- name: Stop ttyAMA0
  ansible.builtin.systemd:
    name: serial-getty@ttyAMA0
    state: stopped
    enabled: false
    masked: true

- name: Disable autologin
  ansible.builtin.file:
    path: /etc/systemd/system/autologin@.service
    state: absent

- name: Remove pi user
  ansible.builtin.user:
    name: pi
    state: absent
    remove: true

- name: Remove pi sudo
  ansible.builtin.file:
    path: /etc/sudoers.d/010_pi-nopasswd
    state: absent

- name: Enable fstrim
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: true
