---
- name: inst-git
  ansible.builtin.package:
    name: git
    state: present

- name: checkout-home-network-repo
  ansible.builtin.git:
    repo: https://github.com/ilikejam/home-network.git
    dest: "{{ config_repo }}"
    version: master
