---
- name: Disable crashkernel
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="console=ttyS0,115200n8 no_timer_check net.ifnames=0 crashkernel={{ crashkernel }}"'
  notify: kernel-changed
  when: ansible_facts['os_family'] == "RedHat"
