---
- name: inst-pidisplay-reqs
  apt:
    state: present
    name:
      - python3-pip
      - python-setuptools
      - python3-pil
      - python-smbus
      - i2c-tools
      - fonts-dejavu

- name: inst-pip-pidisplay-reqs
  pip:
    executable: pip3
    name:
      - adafruit-circuitpython-ssd1306
      - flask
      - flask-wtf

- name: user-display
  user:
    name: display
    groups: i2c

- name: test-i2c
  command: egrep '^dtparam=i2c_arm=on' /boot/config.txt
  register: test_i2c_result
  changed_when: false
  failed_when: false

- name: enable-i2c
  command: raspi-config nonint do_i2c 0
  when: test_i2c_result.rc != 0

- name: unitfile-pidisplay
  template:
    src: pidisplay.service.j2
    dest: /etc/systemd/system/pidisplay.service
    mode: 0644

- name: service-pidisplay
  systemd:
    name: pidisplay
    enabled: true
    daemon_reload: true
