---
- name: debian | Add docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: debian | Add docker apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: debian | Install docker-ce
  ansible.builtin.package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: debian | Add docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
    mode: '0644'
    owner: root
    group: root
  notify: Restart docker

- name: debian | Start+enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
