---
- name: debian | Add docker prereqs
  ansible.builtin.package:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - libffi-dev

- name: debian | Add docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: debian | Add docker apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: debian | Install docker-ce
  ansible.builtin.package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
      - python3-pip

- name: debian | Remove python-configparser
  ansible.builtin.package:
    state: absent
    name: python-configparser

- name: debian | Install docker pip
  ansible.builtin.pip:
    name: docker
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"

- name: debian | Install docker-compose
  ansible.builtin.pip:
    name: docker-compose
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"

- name: debian | Add docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
    mode: '0644'
    owner: root
    group: root
  notify: docker-changed

- name: debian | Start+enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
