---
- name: docker-pre-pkgs
  package:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - libffi-dev

- name: docker-apt-key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: docker-repo
  apt_repository:
    repo: "deb https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: install-docker-ce
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
      - python-pip

- name: docker-pre-pks-rm
  package:
    state: absent
    name: python-configparser

- name: pip-docker
  pip:
    name: docker

- name: install-docker-compose
  pip:
    name: docker-compose
    executable: pip3

- name: file-etc-docker-daemon-json
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
    mode: '0644'
    owner: root
    group: root
  notify: docker-changed

- name: service-docker
  service:
    name: docker
    state: started
    enabled: true
