---
- name: Include redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Get docker user
  ansible.builtin.getent:
    database: group
    key: docker

- name: Set docker GID fact
  ansible.builtin.set_fact:
    docker_gid: "{{ getent_group.docker[1] }}"

- name: Create /var/dockerbind
  ansible.builtin.file:
    path: /var/dockerbind
    state: directory
    mode: '0755'
    owner: root
    group: root
