---
- include_tasks: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: getent-docker-gid
  ansible.builtin.getent:
    database: group
    key: docker

- name: set-docker-gid
  ansible.builtin.set_fact:
    docker_gid: "{{ getent_group.docker[1] }}"

- name: dir-var-dockerbind
  ansible.builtin.file:
    path: /var/dockerbind
    state: directory
    mode: '0755'
    owner: root
    group: root
