---
plugin: community.digitalocean.digitalocean
api_token: "{{ lookup('community.general.bitwarden', 'DO_API_TOKEN', field='password')[0] }}"
attributes:
  - tags
  - id
  - name
  - networks
  - region
keyed_groups:
  - key: do_tags
leading_separator: false
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first
groups:
  digitalocean: true
