---
- hosts: all

  pre_tasks:
    - name: set-hostname
      hostname:
        name: "{{ hostname }}"
    - include_role:
        name: apt-update

  roles:
    - global-handlers
    - repos
    - dave
    - root
    - linux-tools
    - timezone
