---
- hosts: all

  pre_tasks:
    - name: set-hostname
      hostname:
        name: "{{ hostname }}"
    - name: include-apt-update
      include_role:
        name: apt-update

  roles:
    - global_handlers
    - repos
    - dave
    - root
    - linux-tools
    - timezone
