---
- name: "Profile: all"
  hosts: all
  pre_tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    - name: Include apt-update
      ansible.builtin.include_role:
        name: apt-update
  roles:
    - global_handlers
    - repos
    - dave
    - root
    - linux-tools
    - timezone
